services:

  # OTEL Collector to receive logs, metrics and traces from the application
  # plus a UI to query logs, traces and metrics and visualize them.
  otel-lgtm:
    image: grafana/otel-lgtm:0.19.0@sha256:d2f556b1033095d42fd6b5091ed9a091fd58793767f672b3086a4c98a9beb2d1

    ports:
      - 3000:3000 # UI
      - 4317:4317 # OTLP over gRPC for logs, metrics and traces
      - 4318:4318 # OTLP over HTTP for logs, metrics and traces
      - 9090:9090 # Prometheus
