services:

  # OTEL Collector to receive logs, metrics and traces from the application
  # plus a UI to query logs, traces and metrics and visualize them.
  otel-lgtm:
    image: grafana/otel-lgtm:0.18.1@sha256:bf7bfb9c216f240bd930b278049568e8f8500adcee808c076a556bc767544408

    ports:
      - 3000:3000 # UI
      - 4317:4317 # OTLP over gRPC for logs, metrics and traces
      - 4318:4318 # OTLP over HTTP for logs, metrics and traces
      - 9090:9090 # Prometheus
