name: 'Add labels to issues and pull requests'
on:
  issues:
    types: [ opened ]

  pull_request_target:
    branches: [ 'main*' ]

permissions:
  contents: read

jobs:
  add-labels-on-issues:
    permissions:
      issues: write
    if: github.event.repository.fork == false && github.event_name == 'issues' && !github.event.issue.pull_request

    runs-on: ubuntu-24.04

    steps:
      - name: check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Add labels for package found in bug issue descriptions
        shell: pwsh
        run: |
          Import-Module .\build\scripts\add-labels.psm1

          AddLabelsOnIssuesForPackageFoundInBody `
            -issueNumber ${{ github.event.issue.number }} `
            -issueBody $env:ISSUE_BODY
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_BODY: ${{ github.event.issue.body }}

  add-labels-on-pull-requests:
    permissions:
      pull-requests: write
    if: github.event.repository.fork == false && github.event_name == 'pull_request_target'

    runs-on: ubuntu-24.04

    steps:
      - name: check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.repository.default_branch }} # Note: Do not run on the PR branch we want to execute add-labels.psm1 from main on the base repo only because pull_request_target can see secrets

      - name: Add labels for files changed on pull requests
        shell: pwsh
        run: |
          Import-Module .\build\scripts\add-labels.psm1

          AddLabelsOnPullRequestsBasedOnFilesChanged `
            -pullRequestNumber ${{ github.event.pull_request.number }} `
            -labelPackagePrefix 'pkg:'
        env:
          GH_TOKEN: ${{ github.token }}
