# Called by ci.yml to build & test project files
# See: https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
name: Build Component

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      project-build-commands:
        default: ''
        required: false
        type: string
      code-cov-name:
        required: true
        type: string
      code-cov-prefix:
        default: 'unittests'
        required: false
        type: string
      os-list:
        default: '[ "windows-latest", "windows-11-arm", "ubuntu-22.04", "ubuntu-22.04-arm" ]'
        required: false
        type: string
      tfm-list:
        default: '[ "net462", "net8.0", "net9.0", "net10.0" ]'
        required: false
        type: string

permissions:
  contents: read

jobs:
  build-test:

    strategy:
      fail-fast: false # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        os: ${{ fromJSON(inputs.os-list) }}
        version: ${{ fromJSON(inputs.tfm-list) }}
        exclude:
        - os: ubuntu-22.04
          version: net462
        - os: ubuntu-22.04-arm
          version: net462
        - os: ubuntu-22.04-arm
          version: net10.0
        - os: windows-11-arm
          version: net10.0

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        # Note: By default GitHub only fetches 1 commit. MinVer needs to find
        # the version tag which is typically NOT on the first commit so we
        # retrieve them all.
        fetch-depth: 0

    - name: Setup previous .NET runtimes
      uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
      with:
        dotnet-version: |
          8.0.x
          9.0.x

    - name: Setup .NET
      uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0

    - name: dotnet restore ${{ inputs.project-name }}
      run: dotnet restore ${{ inputs.project-name }} ${{ inputs.project-build-commands }}

    - name: dotnet build ${{ inputs.project-name }}
      run: dotnet build ${{ inputs.project-name }} --configuration Release --no-restore ${{ inputs.project-build-commands }}

    - name: dotnet test ${{ inputs.project-name }}
      run: >
        dotnet test ${{ inputs.project-name }}
        --collect:"Code Coverage"
        --results-directory:TestResults
        --framework ${{ matrix.version }}
        --configuration Release
        --no-restore
        --no-build
        --logger:"console;verbosity=detailed"
        --logger:"GitHubActions;report-warnings=false"
        --logger:"junit;LogFilePath=TestResults/junit.xml"
        -- RunConfiguration.DisableAppDomain=true

    - name: Install coverage tool
      run: dotnet tool install -g dotnet-coverage

    - name: Merging test results
      run: dotnet-coverage merge -f cobertura -o ./TestResults/Cobertura.xml ./TestResults/**/*.coverage

    - name: Upload code coverage ${{ inputs.code-cov-prefix }}-${{ inputs.code-cov-name }}
      uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
      continue-on-error: true # Note: Don't fail for upload failures
      env:
        OS: ${{ matrix.os }}
        TFM: ${{ matrix.version }}
      with:
        files: TestResults/Cobertura.xml
        env_vars: OS,TFM
        flags: ${{ inputs.code-cov-prefix }}-${{ inputs.code-cov-name }}
        name: Code Coverage for ${{ inputs.code-cov-prefix }}-${{ inputs.code-cov-name }} on [${{ matrix.os }}.${{ matrix.version }}]
        codecov_yml_path: .github/codecov.yml
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload test results ${{ inputs.code-cov-prefix }}-${{ inputs.code-cov-name }}
      if: ${{ !cancelled() && hashFiles('./**/TestResults/junit.xml') != '' }}
      uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
      with:
        env_vars: OS,TFM
        flags: ${{ inputs.code-cov-prefix }}-${{ inputs.code-cov-name }}
        name: Test results for ${{ inputs.code-cov-prefix }}-${{ inputs.code-cov-name }} on [${{ matrix.os }}.${{ matrix.version }}]
        report_type: test_results
        token: ${{ secrets.CODECOV_TOKEN }}
