# Called by ci.yml to run documentation build
# See: https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
name: Build docfx

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-docfx-build:
    runs-on: windows-latest

    steps:
    - name: check out code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Setup dotnet
      uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1

    - name: install docfx
      run: dotnet tool install -g docfx

    - name: run .\build\docfx.cmd
      shell: cmd
      run: .\build\docfx.cmd
