name: docfx

on:
  pull_request:
    branches: [ main, metrics ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: check out code
      uses: actions/checkout@v2

    - name: install docfx
      run: choco install docfx -y

    - name: run .\build\docfx.cmd
      shell: cmd
      run: .\build\docfx.cmd
