name: Build examples

on:
  workflow_dispatch:
  push:
    branches: [ 'main*' ]
    paths:
      - 'examples/**'
  pull_request:
    branches: [ 'main*' ]
    paths:
      - 'examples/**'

jobs:
  
  build-test-stable:
    defaults:
      run:
        working-directory: examples
    strategy:
      fail-fast: false  # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        version: [ net462, net6.0, net7.0, net8.0 ]
        exclude:
        - os: ubuntu-latest
          version: net462

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # fetching all

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3

    - name: Install dependencies
      run:
        cd examples
        dotnet restore

    - name: Build
      run:
        cd examples
        dotnet build --configuration Release --no-restore --property:ExposeExperimentalFeatures=false

    - name: Test ${{ matrix.version }}
      run:
        cd examples
        dotnet test **/bin/**/${{ matrix.version }}/*.Tests.dll --logger:"console;verbosity=detailed"

  build-test-experimental:
    defaults:
      run:
        working-directory: examples
    strategy:
      fail-fast: false  # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        version: [ net462, net6.0, net7.0, net8.0 ]
        exclude:
        - os: ubuntu-latest
          version: net462

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # fetching all

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3

    - name: Install dependencies
      run:
        cd examples
        dotnet restore

    - name: Build
      run:
        cd examples
        dotnet build --configuration Release --no-restore --property:ExposeExperimentalFeatures=true

    - name: Test ${{ matrix.version }}
      run:
        cd examples
        dotnet test **/bin/**/${{ matrix.version }}/*.Tests.dll --logger:"console;verbosity=detailed"
