# Called by ci.yml to perform markdown linting
# See: https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
name: Lint - Markdown

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-markdownlint:
    runs-on: ubuntu-24.04

    steps:
    - name: check out code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: run markdownlint
      uses: DavidAnson/markdownlint-cli2-action@07035fd053f7be764496c0f8d8f9f41f98305101 # v22.0.0
      with:
        globs: |
          **/*.md
          !.github/**/*.md
