# Called by ci.yml to perform general linting
# See: https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
name: Lint - Spelling & Encoding

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-misspell:
    runs-on: ubuntu-22.04

    steps:
    - name: check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: install misspell
      run: |
        curl -L -o ./install-misspell.sh https://git.io/misspell
        sh ./install-misspell.sh

    - name: run misspell
      run: ./bin/misspell -error .

  run-sanitycheck:
    runs-on: ubuntu-22.04

    steps:
    - name: check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: detect non-ASCII encoding and trailing space
      run: python3 ./build/scripts/sanitycheck.py
