# Called by ci.yml to perform AOT validation
# See: https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
name: Publish & Verify AOT Compatibility

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-verify-aot-compat:

    strategy:
      fail-fast: false # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        os: [ ubuntu-22.04, windows-latest ]
        version: [ net8.0, net9.0, net10.0 ]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

    - name: Setup dotnet
      uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0

    - name: publish AOT testApp, assert static analysis warning count, and run the app
      shell: pwsh
      run: .\build\scripts\test-aot-compatibility.ps1 ${{ matrix.version }}
