# Called by ci.yml to perform AOT validation
# See: https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
name: Publish & Verify AOT Compatibility

on:
  workflow_call:

jobs:
  run-verify-aot-compat:

    strategy:
      fail-fast: false # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        version: [ net8.0, net9.0 ]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x

    - name: publish AOT testApp, assert static analysis warning count, and run the app
      shell: pwsh
      run: .\build\test-aot-compatibility.ps1 ${{ matrix.version }}
