# Called by ci.yml to perform AOT validation
# See: https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
name: Publish & Verify AOT Compatibility

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-verify-aot-compat:

    strategy:
      fail-fast: false # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        os: [ ubuntu-22.04, windows-latest ]
        version: [ net8.0, net9.0, net10.0 ]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Setup dotnet
      uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0

    - name: publish AOT testApp, assert static analysis warning count, and run the app
      shell: pwsh
      run: .\build\scripts\test-aot-compatibility.ps1 ${{ matrix.version }}
